version: '3.8'
services:
  nginx:
      container_name: nginx
      image: nginx:1.15.8-alpine
      ports:
        - "8080:80"
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
      #   # Laravel 10
      #   - ./login-and-registration/public:/var/www/laravel10/public
      #   # OSP Portal
      #   - ../../MPWT/OSSP/web-admin/public:/var/www/ossp-portal/public
      #   # OSP Bank API
      #   - ../../MPWT/OSSP/ossp-api-v2/public:/var/www/ossp-api-v2/public
      # OSR API NEW VERSION
        - ../../MPWT/OSSR/osr-new-api-version/public:/var/www/osr-new-api-version/public
      # Error Page
        - ./error.html:/usr/share/nginx/html/error.html
      networks:
        - ossr_api 
networks:
  ossr_api:
    external: true